### ISSUE TITLE
Bad icon for Download

### ISSUE THREAD

**Issue by j-degreef** [alexanderjeurissen/ranger_devicons#10]
Hi,

I have a bad icon for the Download directory (see pic).
I seems this icon is not present in my fonts (tested with DejaVu Sans Mono and SauceCodePro Nerd Font from NerdFont).

And btw why the Makefile installs devicons.py in the Ranger folder and devicons_linemode.py in the plugins folder ? 

Cheers.
![2017-10-03-144101_1366x768_scrot](https://user-images.githubusercontent.com/6998555/31126044-c734a6cc-a84a-11e7-88df-21f54268ffb7.png)

**Comment by alexanderjeurissen** [comment]
Hi @j-degreef apologies for not getting back to you sooner. I just checked using the latest commit on Master and using `FireCode Mono Nerd Font` and the downloads folder shows up correctly:

<img width="621" alt="screen shot 2017-10-26 at 5 53 51 pm" src="https://user-images.githubusercontent.com/1220084/32063247-f5d33adc-ba76-11e7-8a8f-58f4761e4c4c.png">

Can you try redownloading the font your using and making sure your using the latest revision of this plugin ? if that doesn't resolve it you could opt for removing the ranger folder using `rm -rf ~/.config/ranger` and recopying the default config `ranger --copy-config=all` and running the make file again.

regarding the makefile, I tried putting them both in the same directory, but ran into weird errors and behavior which is why I chose to use the current folder layout, I haven't retried it on the latest ranger version and the issues I ran into back when I originally created this plugin might have been resolved so I'll look into that.

**Comment by alexanderjeurissen** [comment]
I'm closing this out due to inactivity.

**Comment by j-degreef** [comment]
Hi,

Sorry but I had forgotten about this issue. I had replaced the problematic character in my config file and forget about it.
I've tested with your font, except I've not found FireCode but FuraCode :-/
The problem is solved with this font but I've another problem, see screen  capture.
![font_problem](https://user-images.githubusercontent.com/6998555/37052574-f3b8c28e-2179-11e8-810b-0199038e799b.jpg)
And all > are replaced by a little arrow and I cannot type < anymore.
