### ISSUE TITLE
Support plain unicode

### ISSUE THREAD

**Issue by eMPee584** [alexanderjeurissen/ranger_devicons#14]
While the patched fonts will definitely offer an infinitely bigger space of options, why not use the glyphs already in unicode? That adds portability, even if at the cost of versatility & blingness ..
📁📂🗃️🗄️🎞️📽️🎼🎵🎶🖼️⚒️

**Comment by alexanderjeurissen** [comment]
Hi @eMPee584 Thanks for chiming in. Whilst I like the idea of supporting a unicode fallback, I still think that I'd like to support the patched font implementation mainly because of the infinitely bigger space of options.

To set some expectations: I have access to a patched font on all my machines and rarely use ranger in ssh sessions, as such this is really low on my priority list and I thus don't expect to start working on this anytime soon.

**Comment by marcbelmont** [comment]
@eMPee584, here's my plugin that uses Unicode icons.
https://gist.github.com/marcbelmont/c12d2fd2519a372d3b347f665b37e74a#gistcomment-3240106

**Comment by SuperSandro2000** [comment]
@marcbelmont Can you do a PR with this?

**Comment by marcbelmont** [comment]
I have decided to not use ranger_devicons. The Linemode I wrote is standalone. Install instructions:
 https://gist.github.com/marcbelmont/c12d2fd2519a372d3b347f665b37e74a#gistcomment-3240106
