### ISSUE TITLE
It does’t work well on urxvt

### ISSUE THREAD

**Issue by sontekliu** [alexanderjeurissen/ranger_devicons#53]
It does‘t work well on urxvt， The icon can’t be show well.
![20191014_000335](https://user-images.githubusercontent.com/16081767/66718467-e890b680-ee16-11e9-87e8-dcaca757fd18.png)

**Comment by duffydack** [comment]
That's probably just urxvt not supporting wide glyphs.  

![grim-173737](https://user-images.githubusercontent.com/41839511/66718863-8917b400-ede0-11e9-9b6f-8c30eefd71f9.png)

Which is why I use a patched version, [rxvt-unicode-cvs-patched-wideglyphs](https://aur.archlinux.org/packages/rxvt-unicode-cvs-patched-wideglyphs/)

**Comment by sontekliu** [comment]
I see, Thank you

**Comment by fn-ix** [comment]
Just use an unpatched font for the text and load the symbols as a separate font with the desired size in `Xresources`, e.g.
````
URxvt.font:                   xft:Fira Mono:size=12:antialias=true,\
                              xft:FuraMono Nerd Font Mono:size=12
````
