### ISSUE TITLE
"Invisible" Icons

### ISSUE THREAD

**Issue by mridle582** [alexanderjeurissen/ranger_devicons#67]
Hello,
I hope all is well with you. I am currently using the patched Source Code Pro Font (aka Sauce Code Pro Nerd Font) and for some reason the icons are invisible in ranger but visible when I open vim. Any advice would be appreciated.

Thanks

![2020-09-19-02:42:16-screenshot](https://user-images.githubusercontent.com/68788406/93660951-fd5fcc00-fa21-11ea-8978-415aabe07dea.png)
![2020-09-19-02:42:40-screenshot](https://user-images.githubusercontent.com/68788406/93660952-fdf86280-fa21-11ea-9265-10d09c17fbef.png)
![2020-09-19-02:44:58-screenshot](https://user-images.githubusercontent.com/68788406/93660969-241e0280-fa22-11ea-9baa-7ffdd9c93b52.png)
![2020-09-19-02:47:03-screenshot](https://user-images.githubusercontent.com/68788406/93661026-824ae580-fa22-11ea-8008-23918fa1ecf3.png)

**Comment by filipeoliv02** [comment]
Greetings,
I also am experiencing this issue. Any help would be great. I already uninstalled and installed back again, my terminal, ranger, and even zsh just so I could figure out what was causing the problem. I already checked my configs and I still can't find nothing that lead me to this. I can only conclude this is a bug, since I can properly see the icons in vim as well.

**Comment by dionisisNik** [comment]
I fixed this problem on my machine by setting my locale correctly.

1. See the output of 'locale' command in terminal.

2. If it there exists a 'LANG=C' then the devicons don't work. (And your locale is not set up correctly.)

Here is how to setup your [locale](https://wiki.archlinux.org/index.php/locale). See the section 'Setting the locale', it should be pretty easy to fix. 
I for example had to create /etc/locale.conf with 'LANG=en_GB.UTF-8' as contents because I didn't even have it.

**Comment by mridle582** [comment]
> I fixed this problem on my machine by setting my locale correctly.
> 
> 1. See the output of 'locale' command in terminal.
> 2. If it there exists a 'LANG=C' then the devicons don't work. (And your locale is not set up correctly.)
> 
> Here is how to setup your [locale](https://wiki.archlinux.org/index.php/locale). See the section 'Setting the locale', it should be pretty easy to fix.
> I for example had to create /etc/locale.conf with 'LANG=en_GB.UTF-8' as contents because I didn't even have it.
> 
> (Solution on Arch Linux)

Thanks! That worked. How can I 'close' this issue?

**Comment by filipeoliv02** [comment]
> I fixed this problem on my machine by setting my locale correctly.
> 
> 1. See the output of 'locale' command in terminal.
> 2. If it there exists a 'LANG=C' then the devicons don't work. (And your locale is not set up correctly.)
> 
> Here is how to setup your [locale](https://wiki.archlinux.org/index.php/locale). See the section 'Setting the locale', it should be pretty easy to fix.
> I for example had to create /etc/locale.conf with 'LANG=en_GB.UTF-8' as contents because I didn't even have it.
> 
> (Solution on Arch Linux)

Yes that really was the problem. How silly of me, I really thought I did all the steps in the arch wiki while setting the locales but I guess I missed that. Really thankful for your help kind stranger.
Greetings.
