### ISSUE TITLE
No fallback icons (Source Code Pro patched NERDfont + urxvt)

### ISSUE THREAD

**Issue by HallowDance** [alexanderjeurissen/ranger_devicons#73]
**Describe the bug**
There are no icons for pdf files - they appear as missing symbol boxes. That's also true for a lot of other file types. 

**To Reproduce**
Open `ranger` in `urxvt`

Relevant .Xresources:

` URxvt*font:                     xft:SauceCodePro\ Nerd \Font:size=10,xft:symbola:size=10:minspace=False`

**Expected behavior**
It would be nice to have a fallback icon.

**Screenshots**
![Selection_364](https://user-images.githubusercontent.com/16612493/104443206-cac47b00-559e-11eb-9028-71aadac48e5e.png)

**Environment**
 - urxvt
 - zsh 5.8

**Comment by alexanderjeurissen** [comment]
Good find, it would indeed be nice to have a default fallback icon for items that don't match any known file extension.

I'd be open for a PR that addresses this. @HallowDance is this something you'd like to take a stab at ?

**Comment by jeffmhubbard** [comment]
@HallowDance The think the issue is with URxvt. You need to have a patched version of URxvt. The second line of `urxvt --help` will show what options URxvt was compiled with. If you don't see `wide-glyphs` listed, you'll see boxes when characters are too wide. 

I can reproduce your issue on Arch:
- Install `rxvt-unicode` from repos. 
- Install `nerd-fonts-source-code-pro` from AUR. 
- Run `fc-cache -frv`. 
- Add `URxvt*font: Xft:SauceCodePro Nerd Font:size=10` to `~/.Xresources`. 
- Logout; login. 
- Start `ranger`. 
- See some icons, but boxes for others. Both `pdf` and `docx` are boxes.

To resolve:
- Install `rxvt-unicode-cvs-patched-wideglyphs` from AUR.
- Start `ranger`.
- See icons everywhere. Both `pdf` and `docx` have icons.

**Comment by HallowDance** [comment]
Thank you, building `rxvt-unicode-cvs-patched-wideglyphs` has resolved the issue!
